## ASSIGNMENT 1

1. 2024/DSC/0091/SS
2. 2024/DSC/0010/SS
3. 2024/DSC/0014/SS
4. 2024/DSC/0090/SS
5. 2024/DSC/0064/SS
6. 2024/DSC/007/SS
7. 2024/DSC/0056/SS

In [1]:
import numpy as np

In [2]:
A = np.array([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
print(A)

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


##### no 1

#### Part i)

In [3]:
#A = np.array([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
a = np.array([[1],[1],[1],[1]])
Aa = np.hstack((A, a))
print(Aa)#Part i) Adding a new colum

[[ 2  2  3  1]
 [-2  7  4  1]
 [-3 -3 -4  1]
 [-8  2  3  1]]


In [4]:
det = np.linalg.det(Aa)
print(det) 

-299.99999999999994


#### Part ii)

In [5]:
A_r = np.delete(A, 3, axis=0)
print(A_r) # part ii) deleting the row

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]]


In [6]:
if det!= 0:
    print('invertable')
else:
    print('not invertable')

invertable


In [7]:
A = np.array([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
A_T= np.transpose(A)
print(A_T)

[[ 2 -2 -3 -8]
 [ 2  7 -3  2]
 [ 3  4 -4  3]]


In [8]:
AAT= np.dot(A, A_T)
AAT

array([[ 17,  22, -24,  -3],
       [ 22,  69, -31,  42],
       [-24, -31,  34,   6],
       [ -3,  42,   6,  77]])

In [9]:
det = np.linalg.det(AAT)
print(det)

3.3772984409097314e-12


** Yes AAT is invertable because the determinant is not equal to zero **

In [10]:
A = np.array([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
A_T = np.transpose(A)
print(A_T)

[[ 2 -2 -3 -8]
 [ 2  7 -3  2]
 [ 3  4 -4  3]]


In [11]:
ATA = np.dot(A_T, A)
print(A_T,A)

[[ 2 -2 -3 -8]
 [ 2  7 -3  2]
 [ 3  4 -4  3]] [[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


In [12]:
determinant = np.linalg.det(ATA)
determinant

np.float64(45642.00000000001)

#### no.2

In [13]:
x = np.array([[25, 2], [5, 26], [3, 7]])
x.shape

(3, 2)

In [14]:
x = np.array([[25, 2], [5, 26], [3, 7]])
T_x = np.transpose(x)
T_x

array([[25,  5,  3],
       [ 2, 26,  7]])

In [15]:
x = np.array([[25, 2], [5, 26], [3, 7]])
X_S = np.dot(3,x)
print(X_S)

[[75  6]
 [15 78]
 [ 9 21]]


In [21]:
matrix_A=np.array([[3, 4], [5, 6], [7, 8]])
product =np.dot(T_x,matrix_A)
product

array([[121, 154],
       [185, 220]])

In [22]:
inverse = np.linalg.inv(product)
print(inverse)

[[-0.11764706  0.08235294]
 [ 0.09893048 -0.06470588]]


### No.3

#### Part 1)

In [ ]:
E = [25,2,5]
x = np.array(E)
print(x)

##### Part 2)

In [ ]:
shape_E =np.shape(x)
shape_E

#### Part3) 

In [17]:
T_E =np.transpose(x)
T_E

array([[25,  5,  3],
       [ 2, 26,  7]])

#### Part 4)

In [18]:
N_E = np.linalg.norm(x)
N_E

np.float64(37.255872020394314)